import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { AuthProvider } from "@/contexts/AuthContext";
// import LayoutClient from "@/components/landing/LayoutClient"; // ถ้ามีใช้งานให้เปิดไว้ครับ

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ครอบ Providers ที่นี่เพื่อให้ทุกหน้าใช้งาน useLanguage ได้ */}
        <AuthProvider>
          <LanguageProvider>
            {children}
            <Toaster richColors />
          </LanguageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}