"use client";

export const donateThemes = [
  {
    id: "v2-default",
    name: "V2 Default",
    preview: "from-slate-900 via-slate-800 to-slate-950",
    accent: "from-cyan-500 to-blue-500",
    primary: "#06B6D4",
    secondary: "#3B82F6",
    background: "#0B0F19",
  },
  {
    id: "aquamarine",
    name: "AquaMarine",
    preview: "from-teal-900 via-cyan-900 to-slate-950",
    accent: "from-teal-400 to-cyan-400",
    primary: "#2DD4BF",
    secondary: "#22D3EE",
    background: "#081F26",
  },
  {
    id: "midnight-purple",
    name: "Midnight Purple",
    preview: "from-purple-950 via-violet-950 to-slate-950",
    accent: "from-purple-500 to-pink-500",
    primary: "#8B5CF6",
    secondary: "#EC4899",
    background: "#120A25",
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    preview: "from-orange-950 via-red-950 to-slate-950",
    accent: "from-orange-500 to-red-500",
    primary: "#F97316",
    secondary: "#EF4444",
    background: "#24100A",
  },
  {
    id: "forest-green",
    name: "Forest Green",
    preview: "from-emerald-950 via-green-950 to-slate-950",
    accent: "from-emerald-500 to-teal-500",
    primary: "#10B981",
    secondary: "#14B8A6",
    background: "#071A12",
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    preview: "from-pink-950 via-rose-950 to-slate-950",
    accent: "from-pink-500 to-rose-500",
    primary: "#EC4899",
    secondary: "#F43F5E",
    background: "#240915",
  },
];

export const donationDecorationPresets = [
  {
    id: "ice-default",
    name: "Ice Default",
    description: "โทนน้ำแข็งเดิมของฟอร์มโดเนท",
    preview: "from-sky-950 via-cyan-900 to-slate-950",
    badge: "Default",
    themeId: "v2-default",
    settingsPatch: {
      snowEffect: true,
      glowEffect: true,
    },
    formTheme: {
      primary: "186, 230, 253",
      secondary: "147, 197, 253",
      accent: "255, 255, 255",
      base: "4, 15, 30",
      baseSecondary: "12, 28, 48",
      text: "255, 255, 255",
      mutedText: "255, 255, 255",
      buttonText: "13, 42, 58",
      buttonBackground: "linear-gradient(120deg, rgb(186, 230, 253), rgb(255, 255, 255))",
      cardBackground: "linear-gradient(180deg, rgba(4, 15, 30, 0.96), rgba(9, 24, 44, 0.94))",
      innerBackground: "rgba(4, 15, 30, 0.95)",
    },
    sectionTheme: {
      primary: "186, 230, 253",
      secondary: "147, 197, 253",
      accent: "255, 255, 255",
      base: "4, 15, 30",
      baseSecondary: "12, 28, 48",
      text: "255, 255, 255",
      mutedText: "255, 255, 255",
      buttonText: "13, 42, 58",
      buttonBackground: "linear-gradient(120deg, rgb(186, 230, 253), rgb(255, 255, 255))",
      cardBackground: "linear-gradient(180deg, rgba(4, 15, 30, 0.96), rgba(9, 24, 44, 0.94))",
      innerBackground: "rgba(4, 15, 30, 0.95)",
    },
    sectionDecorations: {
      panelLeft: {
        src: "/imgs/ice.png",
        alt: "section-left",
        className: "pointer-events-none absolute -top-1 left-0 w-10 z-20 opacity-90",
      },
      panelRight: {
        src: "/imgs/ice.png",
        alt: "section-right",
        className: "pointer-events-none absolute -top-2 -right-2 w-30 scale-x-[-1] z-20 opacity-90",
      },
    },
    decorations: {
      step1Left: {
        src: "/imgs/ice.png",
        alt: "decoration-step-1-left",
        className: "pointer-events-none absolute -top-1 left-0 w-10 z-20 opacity-90",
      },
      step1Right: {
        src: "/imgs/ice_bar_1.png",
        alt: "decoration-step-1-right",
        className: "pointer-events-none absolute -top-12 -right-5 w-90 z-20 opacity-90",
      },
      step2Left: {
        src: "/imgs/ice_bar_2.png",
        alt: "decoration-step-2-left",
        className: "pointer-events-none absolute -top-1 -left-1 w-20 z-20 opacity-90",
      },
      step2Right: {
        src: "/imgs/ice_bar_2.png",
        alt: "decoration-step-2-right",
        className: "pointer-events-none absolute -top-7 -right-3 w-90 z-20 opacity-90",
      },
      step3Left: {
        src: "/imgs/ice_bar_2.png",
        alt: "decoration-step-3-left",
        className: "pointer-events-none absolute -top-1 -left-1 w-20 z-20 opacity-90",
      },
      step3Right: {
        src: "/imgs/ice_bar_2.png",
        alt: "decoration-step-3-right",
        className: "pointer-events-none absolute -top-7 -right-3 w-90 z-20 opacity-90",
      },
    },
  },
  {
    id: "chinese-new-year",
    name: "Chinese New Year",
    description: "แดงทองพร้อมลวดลายมงคลสำหรับช่วงเทศกาล",
    preview: "from-red-950 via-red-800 to-amber-700",
    badge: "Seasonal",
    themeId: "sunset-orange",
    settingsPatch: {
      snowEffect: false,
      glowEffect: true,
    },
    formTheme: {
      primary: "247, 197, 72",
      secondary: "220, 38, 38",
      accent: "255, 231, 179",
      base: "38, 10, 10",
      baseSecondary: "82, 18, 18",
      text: "255, 248, 235",
      mutedText: "255, 228, 200",
      buttonText: "103, 18, 18",
      buttonBackground: "linear-gradient(120deg, rgb(247, 197, 72), rgb(255, 231, 179))",
      cardBackground: "linear-gradient(180deg, rgba(44, 10, 10, 0.97), rgba(92, 18, 18, 0.95))",
      innerBackground: "linear-gradient(180deg, rgba(55, 11, 11, 0.96), rgba(83, 17, 17, 0.94))",
    },
    sectionTheme: {
      primary: "247, 197, 72",
      secondary: "220, 38, 38",
      accent: "255, 231, 179",
      base: "38, 10, 10",
      baseSecondary: "82, 18, 18",
      text: "255, 248, 235",
      mutedText: "255, 228, 200",
      buttonText: "103, 18, 18",
      buttonBackground: "linear-gradient(120deg, rgb(247, 197, 72), rgb(255, 231, 179))",
      cardBackground: "linear-gradient(180deg, rgba(44, 10, 10, 0.97), rgba(92, 18, 18, 0.95))",
      innerBackground: "linear-gradient(180deg, rgba(55, 11, 11, 0.96), rgba(83, 17, 17, 0.94))",
    },
    sectionDecorations: {
      panelLeft: {
        src: "/imgs/cny/transparent/festive_chinese_new_year_corner_ornament-transparent.png",
        alt: "cny-section-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-16 z-20 opacity-95",
      },
      panelRight: {
        src: "/imgs/cny/transparent/festive_chinese_new_year_corner_ornament-transparent.png",
        alt: "cny-section-right",
        className: "pointer-events-none absolute -top-3 -right-3 w-16 -scale-x-100 z-20 opacity-95",
      },
    },
    decorations: {
      step1Left: {
        src: "/imgs/cny/transparent/festive_chinese_new_year_corner_ornament-transparent.png",
        alt: "cny-step-1-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-28 z-20 opacity-95",
      },
      step1Right: {
        src: "/imgs/cny/transparent/chinese_new_year_festive_header_banner-transparent.png",
        alt: "cny-step-1-right",
        className: "pointer-events-none absolute -top-10 right-0 w-72 z-20 opacity-90",
      },
      step2Left: {
        src: "/imgs/cny/transparent/red_and_gold_cloud_ornament-transparent.png",
        alt: "cny-step-2-left",
        className: "pointer-events-none absolute -top-3 -left-2 w-24 z-20 opacity-95",
      },
      step2Right: {
        src: "/imgs/cny/transparent/festive_chinese_new_year_corner_ornament-transparent.png",
        alt: "cny-step-2-right",
        className: "pointer-events-none absolute -top-3 -right-2 w-24 -scale-x-100 z-20 opacity-95",
      },
      step3Left: {
        src: "/imgs/cny/transparent/red_and_gold_cloud_ornament-transparent.png",
        alt: "cny-step-3-left",
        className: "pointer-events-none absolute -top-2 -left-2 w-20 z-20 opacity-95",
      },
      step3Right: {
        src: "",
        alt: "cny-step-3-right",
        className: "",
      },
    },
  },
  {
    id: "halloween",
    name: "Halloween",
    description: "ม่วงดำส้มกับริบบอน ค้างคาว และโคมฟักทอง",
    preview: "from-violet-950 via-slate-950 to-orange-950",
    badge: "Seasonal",
    themeId: "midnight-purple",
    settingsPatch: {
      snowEffect: false,
      glowEffect: true,
    },
    formTheme: {
      primary: "251, 146, 60",
      secondary: "168, 85, 247",
      accent: "253, 224, 71",
      base: "17, 11, 28",
      baseSecondary: "34, 17, 51",
      text: "248, 245, 255",
      mutedText: "226, 220, 255",
      buttonText: "40, 16, 4",
      buttonBackground: "linear-gradient(120deg, rgb(251, 146, 60), rgb(253, 224, 71))",
      cardBackground: "linear-gradient(180deg, rgba(16, 10, 27, 0.97), rgba(37, 18, 54, 0.95))",
      innerBackground: "linear-gradient(180deg, rgba(20, 10, 31, 0.96), rgba(30, 15, 44, 0.94))",
    },
    sectionTheme: {
      primary: "251, 146, 60",
      secondary: "168, 85, 247",
      accent: "253, 224, 71",
      base: "17, 11, 28",
      baseSecondary: "34, 17, 51",
      text: "248, 245, 255",
      mutedText: "226, 220, 255",
      buttonText: "40, 16, 4",
      buttonBackground: "linear-gradient(120deg, rgb(251, 146, 60), rgb(253, 224, 71))",
      cardBackground: "linear-gradient(180deg, rgba(16, 10, 27, 0.97), rgba(37, 18, 54, 0.95))",
      innerBackground: "linear-gradient(180deg, rgba(20, 10, 31, 0.96), rgba(30, 15, 44, 0.94))",
    },
    sectionDecorations: {
      panelLeft: {
        src: "/imgs/halloween/transparent/elegant_halloween_corner_ornament_decoration-transparent.png",
        alt: "halloween-section-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-18 z-20 opacity-95",
      },
      panelRight: {
        src: "/imgs/halloween/transparent/gothic_halloween_ornament_with_ribbon_and_lantern-transparent.png",
        alt: "halloween-section-right",
        className: "pointer-events-none absolute -top-3 -right-3 w-18 -scale-x-100 z-20 opacity-95",
      },
    },
    decorations: {
      step1Left: {
        src: "/imgs/halloween/transparent/elegant_halloween_corner_ornament_decoration-transparent.png",
        alt: "halloween-step-1-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-24 z-20 opacity-95",
      },
      step1Right: {
        src: "/imgs/halloween/transparent/gothic_halloween_ornament_with_ribbon_and_lantern-transparent.png",
        alt: "halloween-step-1-right",
        className: "pointer-events-none absolute -top-3 -right-2 w-24 -scale-x-100 z-20 opacity-95",
      },
      step2Left: {
        src: "/imgs/halloween/transparent/elegant_halloween_corner_ornament_decoration-transparent.png",
        alt: "halloween-step-2-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-20 z-20 opacity-95",
      },
      step2Right: {
        src: "/imgs/halloween/transparent/elegant_halloween_garland_with_lanterns_and_bats-transparent.png",
        alt: "halloween-step-2-right",
        className: "pointer-events-none absolute -top-7 left-1/2 w-[15rem] -translate-x-1/2 z-20 opacity-85",
      },
      step3Left: {
        src: "/imgs/halloween/transparent/gothic_halloween_ornament_with_ribbon_and_lantern-transparent.png",
        alt: "halloween-step-3-left",
        className: "pointer-events-none absolute -top-3 -left-3 w-20 z-20 opacity-95",
      },
      step3Right: {
        src: "",
        alt: "halloween-step-3-right",
        className: "",
      },
    },
  },
];

export function getDonationDecorationPreset(presetId) {
  return (
    donationDecorationPresets.find((preset) => preset.id === presetId) ||
    donationDecorationPresets[0]
  );
}

const defaultDonationDecorationPreset = getDonationDecorationPreset("ice-default");

export const defaultDonatePageSettings = {
  theme: "v2-default",
  design: {
    glassEffect: true,
    snowEffect: true,
    glowEffect: true,
    compactMode: false,
    cardOpacity: 70,
    backgroundBlur: 35,
    borderRadius: 22,
    decorationPreset: defaultDonationDecorationPreset.id,
    donationFormDecorations: defaultDonationDecorationPreset.decorations,
    donationFormTheme: defaultDonationDecorationPreset.formTheme,
    sectionTheme: defaultDonationDecorationPreset.sectionTheme,
    sectionDecorations: defaultDonationDecorationPreset.sectionDecorations,
  },
  profile: {
    name: "x86",
    handle: "ezdn.app/x86",
    username: "x86",
    bio: "สตรีมเมอร์สาย Competitive 🎮 | เล่น Valorant & LoL | สตรีมทุกวัน 20:00+",
    avatarUrl: "",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e",
    isOnline: true,
    verified: true,
  },
  socials: [
    { id: "facebook", label: "Facebook", href: "https://facebook.com/test", enabled: true },
    { id: "instagram", label: "Instagram", href: "https://instagram.com/test", enabled: true },
    { id: "youtube", label: "YouTube", href: "https://youtube.com/test", enabled: true },
    { id: "tiktok", label: "TikTok", href: "https://tiktok.com/test", enabled: true },
  ],
  donation: {
    pageTitle: "สนับสนุนสตรีมเมอร์",
    minAmount: 20,
    quickAmounts: [10, 20, 50, 100, 200, 500],
    qrCodeUrl: "",
    showQrCode: true,
    allowCustomAmount: true,
    allowAnonymous: true,
    showDonorName: true,
    showMessage: true,
    welcomeMessage: "ขอบคุณที่สนับสนุนกันนะครับ ทุกโดเนทช่วยให้ทำคอนเทนต์ได้ดีขึ้น 💜",
    buttonText: "โดเนทเลย",
  },
  filters: [
    {
      id: "profanity",
      name: "Block Profanity",
      description: "บล็อกคำหยาบและภาษาที่ไม่เหมาะสม",
      enabled: true,
    },
    {
      id: "links",
      name: "Block Links",
      description: "ป้องกันการส่งลิงก์ในข้อความ",
      enabled: true,
    },
    {
      id: "spam",
      name: "Spam Detection",
      description: "ตรวจจับและกรองข้อความสแปมอัตโนมัติ",
      enabled: false,
    },
    {
      id: "anonymous",
      name: "Allow Anonymous",
      description: "อนุญาตให้ผู้โดเนทซ่อนชื่อได้",
      enabled: true,
    },
  ],
  music: {
    enabled: true,
    allowYoutubeRequest: true,
    allowUpload: true,
    showNowPlaying: true,
    showPlaylist: true,
    autoplay: false,
    volume: 65,
    currentSong: {
      title: "Chill Vibes Lo-fi",
      artist: "StudyBeats",
      duration: "3:24",
    },
    playlist: [
      { id: 1, title: "Chill Vibes Lo-fi", duration: "3:24" },
      { id: 2, title: "Neon Dreams", duration: "4:21" },
      { id: 3, title: "Midnight Rain", duration: "2:58" },
    ],
  },
  videos: [
    {
      id: 1,
      title: "Clutch 1v3 Valorant!",
      views: "12.5K",
      duration: "0:45",
      thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e",
      enabled: true,
    },
    {
      id: 2,
      title: "จังหวะพลิกเกมสุดเดือด",
      views: "8.2K",
      duration: "1:20",
      thumbnail: "https://images.unsplash.com/photo-1598550476439-6847785fcea6",
      enabled: true,
    },
    {
      id: 3,
      title: "Ace แบบไม่ให้ตั้งตัว",
      views: "15.1K",
      duration: "0:58",
      thumbnail: "https://images.unsplash.com/photo-1603481546238-487240415921",
      enabled: true,
    },
  ],
  posts: [
    {
      id: 1,
      text: "วันนี้เล่นจัดหนัก Valorant ตั้งแต่ 2 ทุ่ม วันนี้มีท้าทายสุดเดือดครับ 🔥",
      image: "https://images.unsplash.com/photo-1542751110-97427bbecf20",
      enabled: true,
    },
    {
      id: 2,
      text: "เล่น LoL กับเพื่อนๆ สนุกจัด ๆ ไปเลย 🤣",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e",
      enabled: true,
    },
  ],
  gallery: [
    { id: 1, url: "https://images.unsplash.com/photo-1542751371-adc38448a05e", enabled: true },
    { id: 2, url: "https://images.unsplash.com/photo-1598550476439-6847785fcea6", enabled: true },
    { id: 3, url: "https://images.unsplash.com/photo-1603481546238-487240415921", enabled: true },
    { id: 4, url: "https://images.unsplash.com/photo-1511512578047-dfb367046420", enabled: true },
  ],
  schedule: [
    { id: 1, day: "จันทร์", time: "20:00 - 23:00", title: "Valorant", enabled: true },
    { id: 2, day: "อังคาร", time: "20:00 - 23:00", title: "Just Chatting", enabled: true },
    { id: 3, day: "พุธ", time: "20:00 - 00:00", title: "GTA V RP", enabled: true },
    { id: 4, day: "ศุกร์", time: "19:00 - 01:00", title: "Game Night", enabled: true },
    { id: 5, day: "เสาร์", time: "15:00 - 20:00", title: "Special Event", enabled: true },
  ],
  products: [
    {
      id: 1,
      name: "HUB Hoodie",
      price: 590,
      image: "https://images.unsplash.com/photo-1523398002811-999ca8dec234",
      enabled: true,
    },
    {
      id: 2,
      name: "แก้วน้ำ Gamer",
      price: 350,
      image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d",
      enabled: true,
    },
    {
      id: 3,
      name: "Mousepad RGB",
      price: 390,
      image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae",
      enabled: true,
    },
  ],
  recentDonations: {
    enabled: true,
    maxItems: 5,
    showAmount: true,
    showTime: true,
    items: [
      { id: 1, name: "NuttyNat", amount: 500, message: "สู้ๆครับพี่ ✨", time: "2 นาทีที่แล้ว" },
      { id: 2, name: "Pakporn Gamer", amount: 200, message: "เกมมากครับ 🔥", time: "5 นาทีที่แล้ว" },
      { id: 3, name: "Anonymous", amount: 100, message: "โดเนทครับ 💜", time: "10 นาทีที่แล้ว" },
      { id: 4, name: "BossZa", amount: 50, message: "ร้าววววว!", time: "12 นาทีที่แล้ว" },
      { id: 5, name: "RealAum", amount: 20, message: "สนุกมากครับ", time: "18 นาทีที่แล้ว" },
    ],
  },
  display: {
    showProfileHeader: true,
    showDonationForm: true,
    showMusicPanel: true,
    showVideoHighlights: true,
    showDailyContent: true,
    showGallery: true,
    showSchedule: true,
    showProducts: true,
    showRecentDonations: true,
    stickyDonationForm: true,
    showFooter: true,
  },
};

export function getDonateTheme(themeId) {
  return donateThemes.find((theme) => theme.id === themeId) || donateThemes[0];
}
